const PINATA_API_KEY: string = process.env.PINATA_API_KEY as string;
const PINATA_SECRET_API_KEY: string = process.env
  .PINATA_SECRET_API_KEY as string;

const INFURA_PROJECT_KEY = process.env.INFURA_PROJECT_KEY;
const INFURA_PROJECT_SECRET = process.env.INFURA_PROJECT_SECRET;

const IPFS_GATEWAY = process.env.IPFS_GATEWAY;

export {
  IPFS_GATEWAY,
  PINATA_API_KEY,
  PINATA_SECRET_API_KEY,
  INFURA_PROJECT_KEY,
  INFURA_PROJECT_SECRET,
};
