/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  GreeterInterface,
  GreeterInterfaceInterface,
} from "../GreeterInterface";

const _abi = [
  {
    inputs: [],
    name: "some",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class GreeterInterface__factory {
  static readonly abi = _abi;
  static createInterface(): GreeterInterfaceInterface {
    return new utils.Interface(_abi) as GreeterInterfaceInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): GreeterInterface {
    return new Contract(address, _abi, signerOrProvider) as GreeterInterface;
  }
}
